### ISSUE TITLE
hey bro

### ISSUE THREAD

**Issue by EricAn96** [Ahria03/Paint-Project#1]
take this

![among-us-twerk](https://user-images.githubusercontent.com/83483285/154596192-33a91f5b-4cf4-4400-88e0-ac84c9aceeb4.gif)

**Comment by C-Teo** [comment]
hate you lol

**Comment by Gianev** [comment]
Magnificent! I aspire to have something like this because it is amazing.

**Comment by EricAn96** [comment]
> Magnificent! I aspire to have something like this because it is amazing.

Thank you :)
